# PyTorch Basics

In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '4' 

import torch
import numpy as np
torch.manual_seed(1234)

## Tensors

* Scalar is a single number.
* Vector is an array of numbers.
* Matrix is a 2-D array of numbers.
* Tensors are N-D arrays of numbers.

#### Creating Tensors

You can create tensors by specifying the shape as arguments.  Here is a tensor with 5 rows and 3 columns

In [7]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [3]:
describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 4.0624e+05,  4.5696e-41,  7.3640e-32],
        [ 3.0700e-41,  4.4842e-44,  0.0000e+00]])


In [4]:
describe(torch.randn(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


It's common in prototyping to create a tensor with random numbers of a specific shape.

In [5]:
x = torch.rand(2, 3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.7749,  0.8208,  0.2793],
        [ 0.6817,  0.2837,  0.6567]])


You can also initialize tensors of ones or zeros.

In [6]:
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 5.,  5.,  5.],
        [ 5.,  5.,  5.]])


Tensors can be initialized and then filled in place. 

Note: operations that end in an underscore (`_`) are in place operations.

In [7]:
x = torch.Tensor(3,4).fill_(5)
print(x.type())
print(x.shape)
print(x)

torch.FloatTensor
torch.Size([3, 4])
tensor([[ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.]])


Tensors can be initialized from a list of lists

In [8]:
x = torch.Tensor([[1, 2,],  
                  [2, 4,]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 1.,  2.],
        [ 2.,  4.]])


Tensors can be initialized from numpy matrices

In [9]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))
print(npy.dtype)

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.6607,  0.2072,  0.1046],
        [ 0.8505,  0.8420,  0.9717]], dtype=torch.float64)
float64


#### Tensor Types

The FloatTensor has been the default tensor that we have been creating all along

In [11]:
import torch
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])


In [12]:
x = torch.FloatTensor([[1, 2, 3],  
                       [4, 5, 6]])
describe(x)

x = x.long()
describe(x)

x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=torch.int64)
describe(x)

x = x.float() 
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1,  2,  3],
        [ 4,  5,  6]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1,  2,  3],
        [ 4,  5,  6]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])


In [13]:
x = torch.randn(2, 3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.5385, -0.9757,  1.5769],
        [ 0.3840, -0.6039, -0.5240]])


In [14]:
describe(torch.add(x, x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 3.0771, -1.9515,  3.1539],
        [ 0.7680, -1.2077, -1.0479]])


In [15]:
describe(x + x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 3.0771, -1.9515,  3.1539],
        [ 0.7680, -1.2077, -1.0479]])


In [16]:
x = torch.arange(6)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([6])
Values: 
tensor([ 0.,  1.,  2.,  3.,  4.,  5.])


In [17]:
x = x.view(2, 3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])


In [18]:
describe(torch.sum(x, dim=0))
describe(torch.sum(x, dim=1))

Type: torch.FloatTensor
Shape/size: torch.Size([3])
Values: 
tensor([ 3.,  5.,  7.])
Type: torch.FloatTensor
Shape/size: torch.Size([2])
Values: 
tensor([  3.,  12.])


In [42]:
describe(torch.transpose(x, 0, 1))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[ 0.,  3.],
        [ 1.,  4.],
        [ 2.,  5.]])


In [13]:
import torch
x = torch.arange(6).view(2, 3)
describe(x)
describe(x[:1, :2])
describe(x[0, 1])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[ 0.,  1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
1.0


In [19]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 0.,  2.],
        [ 3.,  5.]])


In [20]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.,  1.,  2.],
        [ 0.,  1.,  2.]])


In [21]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

Type: torch.FloatTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 0.,  4.])


Long Tensors are used for indexing operations and mirror the `int64` numpy type

In [22]:
x = torch.LongTensor([[1, 2, 3],  
                      [4, 5, 6],
                      [7, 8, 9]])
describe(x)
print(x.dtype)
print(x.numpy().dtype)

Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])
torch.int64
int64


You can convert a FloatTensor to a LongTensor

In [23]:
x = torch.FloatTensor([[1, 2, 3],  
                       [4, 5, 6],
                       [7, 8, 9]])
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])


### Special Tensor initializations

We can create a vector of incremental numbers

In [24]:
x = torch.arange(0, 10)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])


Sometimes it's useful to have an integer-based arange for indexing

In [25]:
x = torch.arange(0, 10).long()
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9])


## Operations

Using the tensors to do linear algebra is a foundation of modern Deep Learning practices

Reshaping allows you to move the numbers in a tensor around.  One can be sure that the order is preserved.  In PyTorch, reshaping is called `view`

In [26]:
x = torch.arange(0, 20)

print(x.view(1, 20))
print(x.view(2, 10))
print(x.view(4, 5))
print(x.view(5, 4))
print(x.view(10, 2))
print(x.view(20, 1))

tensor([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,
          10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]])
tensor([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]])
tensor([[  0.,   1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.],
        [ 15.,  16.,  17.,  18.,  19.]])
tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.]])
tensor([[  0.,   1.],
        [  2.,   3.],
        [  4.,   5.],
        [  6.,   7.],
        [  8.,   9.],
        [ 10.,  11.],
        [ 12.,  13.],
        [ 14.,  15.],
        [ 16.,  17.],
        [ 18.,  19.]])
tensor([[  0.],
        [  1.],
        [  2.],
        [  3.],
        [  4.],
        [  5.],
        [  6.],
        [  7.],
        [  8.],
        [  9.],
      

We can use view to add size-1 dimensions, which can be useful for combining with other tensors.  This is called broadcasting. 

In [27]:
x = torch.arange(12).view(3, 4)
y = torch.arange(4).view(1, 4)
z = torch.arange(3).view(3, 1)

print(x)
print(y)
print(z)
print(x + y)
print(x + z)

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])
tensor([[ 0.,  1.,  2.,  3.]])
tensor([[ 0.],
        [ 1.],
        [ 2.]])
tensor([[  0.,   2.,   4.,   6.],
        [  4.,   6.,   8.,  10.],
        [  8.,  10.,  12.,  14.]])
tensor([[  0.,   1.,   2.,   3.],
        [  5.,   6.,   7.,   8.],
        [ 10.,  11.,  12.,  13.]])


Unsqueeze and squeeze will add and remove 1-dimensions.

In [28]:
x = torch.arange(12).view(3, 4)
print(x.shape)

x = x.unsqueeze(dim=1)
print(x.shape)

x = x.squeeze()
print(x.shape)

torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4])


all of the standard mathematics operations apply (such as `add` below)

In [29]:
x = torch.rand(3,4)
print("x: \n", x)
print("--")
print("torch.add(x, x): \n", torch.add(x, x))
print("--")
print("x+x: \n", x + x)

x: 
 tensor([[ 0.6662,  0.3343,  0.7893,  0.3216],
        [ 0.5247,  0.6688,  0.8436,  0.4265],
        [ 0.9561,  0.0770,  0.4108,  0.0014]])
--
torch.add(x, x): 
 tensor([[ 1.3324,  0.6686,  1.5786,  0.6433],
        [ 1.0494,  1.3377,  1.6872,  0.8530],
        [ 1.9123,  0.1540,  0.8216,  0.0028]])
--
x+x: 
 tensor([[ 1.3324,  0.6686,  1.5786,  0.6433],
        [ 1.0494,  1.3377,  1.6872,  0.8530],
        [ 1.9123,  0.1540,  0.8216,  0.0028]])


The convention of `_` indicating in-place operations continues:

In [30]:
x = torch.arange(12).reshape(3, 4)
print(x)
print(x.add_(x))

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])
tensor([[  0.,   2.,   4.,   6.],
        [  8.,  10.,  12.,  14.],
        [ 16.,  18.,  20.,  22.]])


There are many operations for which reduce a dimension.  Such as sum:

In [31]:
x = torch.arange(12).reshape(3, 4)
print("x: \n", x)
print("---")
print("Summing across rows (dim=0): \n", x.sum(dim=0))
print("---")
print("Summing across columns (dim=1): \n", x.sum(dim=1))

x: 
 tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])
---
Summing across rows (dim=0): 
 tensor([ 12.,  15.,  18.,  21.])
---
Summing across columns (dim=1): 
 tensor([  6.,  22.,  38.])


#### Indexing, Slicing, Joining and Mutating

In [32]:
x = torch.arange(6).view(2, 3)
print("x: \n", x)
print("---")
print("x[:2, :2]: \n", x[:2, :2])
print("---")
print("x[0][1]: \n", x[0][1])
print("---")
print("Setting [0][1] to be 8")
x[0][1] = 8
print(x)

x: 
 tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])
---
x[:2, :2]: 
 tensor([[ 0.,  1.],
        [ 3.,  4.]])
---
x[0][1]: 
 tensor(1.)
---
Setting [0][1] to be 8
tensor([[ 0.,  8.,  2.],
        [ 3.,  4.,  5.]])


We can select a subset of a tensor using the `index_select`

In [33]:
x = torch.arange(9).view(3,3)
print(x)

print("---")
indices = torch.LongTensor([0, 2])
print(torch.index_select(x, dim=0, index=indices))

print("---")
indices = torch.LongTensor([0, 2])
print(torch.index_select(x, dim=1, index=indices))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]])
---
tensor([[ 0.,  1.,  2.],
        [ 6.,  7.,  8.]])
---
tensor([[ 0.,  2.],
        [ 3.,  5.],
        [ 6.,  8.]])


We can also use numpy-style advanced indexing:

In [34]:
x = torch.arange(9).view(3,3)
indices = torch.LongTensor([0, 2])

print(x[indices])
print("---")
print(x[indices, :])
print("---")
print(x[:, indices])

tensor([[ 0.,  1.,  2.],
        [ 6.,  7.,  8.]])
---
tensor([[ 0.,  1.,  2.],
        [ 6.,  7.,  8.]])
---
tensor([[ 0.,  2.],
        [ 3.,  5.],
        [ 6.,  8.]])


We can combine tensors by concatenating them.  First, concatenating on the rows

In [36]:
x = torch.arange(6).view(2,3)
describe(x)
describe(torch.cat([x, x], dim=0))
describe(torch.cat([x, x], dim=1))
describe(torch.stack([x, x]))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[ 0.,  1.,  2.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  3.,  4.,  5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]]])


We can concentate along the first dimension.. the columns.

In [23]:
x = torch.arange(9).view(3,3)

print(x)
print("---")
new_x = torch.cat([x, x, x], dim=1)
print(new_x.shape)
print(new_x)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]])
---
torch.Size([3, 9])
tensor([[ 0.,  1.,  2.,  0.,  1.,  2.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  3.,  4.,  5.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  6.,  7.,  8.,  6.,  7.,  8.]])


We can also concatenate on a new 0th dimension to "stack" the tensors:

In [24]:
x = torch.arange(9).view(3,3)
print(x)
print("---")
new_x = torch.stack([x, x, x])
print(new_x.shape)
print(new_x)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]])
---
torch.Size([3, 3, 3])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.]]])


#### Linear Algebra Tensor Functions

Transposing allows you to switch the dimensions to be on different axis. So we can make it so all the rows are columsn and vice versa. 

In [25]:
x = torch.arange(0, 12).view(3,4)
print("x: \n", x) 
print("---")
print("x.tranpose(1, 0): \n", x.transpose(1, 0))

x: 
 tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])
---
x.tranpose(1, 0): 
 tensor([[  0.,   4.,   8.],
        [  1.,   5.,   9.],
        [  2.,   6.,  10.],
        [  3.,   7.,  11.]])


A three dimensional tensor would represent a batch of sequences, where each sequence item has a feature vector.  It is common to switch the batch and sequence dimensions so that we can more easily index the sequence in a sequence model. 

Note: Transpose will only let you swap 2 axes.  Permute (in the next cell) allows for multiple

In [26]:
batch_size = 3
seq_size = 4
feature_size = 5

x = torch.arange(batch_size * seq_size * feature_size).view(batch_size, seq_size, feature_size)

print("x.shape: \n", x.shape)
print("x: \n", x)
print("-----")

print("x.transpose(1, 0).shape: \n", x.transpose(1, 0).shape)
print("x.transpose(1, 0): \n", x.transpose(1, 0))

x.shape: 
 torch.Size([3, 4, 5])
x: 
 tensor([[[  0.,   1.,   2.,   3.,   4.],
         [  5.,   6.,   7.,   8.,   9.],
         [ 10.,  11.,  12.,  13.,  14.],
         [ 15.,  16.,  17.,  18.,  19.]],

        [[ 20.,  21.,  22.,  23.,  24.],
         [ 25.,  26.,  27.,  28.,  29.],
         [ 30.,  31.,  32.,  33.,  34.],
         [ 35.,  36.,  37.,  38.,  39.]],

        [[ 40.,  41.,  42.,  43.,  44.],
         [ 45.,  46.,  47.,  48.,  49.],
         [ 50.,  51.,  52.,  53.,  54.],
         [ 55.,  56.,  57.,  58.,  59.]]])
-----
x.transpose(1, 0).shape: 
 torch.Size([4, 3, 5])
x.transpose(1, 0): 
 tensor([[[  0.,   1.,   2.,   3.,   4.],
         [ 20.,  21.,  22.,  23.,  24.],
         [ 40.,  41.,  42.,  43.,  44.]],

        [[  5.,   6.,   7.,   8.,   9.],
         [ 25.,  26.,  27.,  28.,  29.],
         [ 45.,  46.,  47.,  48.,  49.]],

        [[ 10.,  11.,  12.,  13.,  14.],
         [ 30.,  31.,  32.,  33.,  34.],
         [ 50.,  51.,  52.,  53.,  54.]],

        [[ 15

Permute is a more general version of tranpose:

In [27]:
batch_size = 3
seq_size = 4
feature_size = 5

x = torch.arange(batch_size * seq_size * feature_size).view(batch_size, seq_size, feature_size)

print("x.shape: \n", x.shape)
print("x: \n", x)
print("-----")

print("x.permute(1, 0, 2).shape: \n", x.permute(1, 0, 2).shape)
print("x.permute(1, 0, 2): \n", x.permute(1, 0, 2))

x.shape: 
 torch.Size([3, 4, 5])
x: 
 tensor([[[  0.,   1.,   2.,   3.,   4.],
         [  5.,   6.,   7.,   8.,   9.],
         [ 10.,  11.,  12.,  13.,  14.],
         [ 15.,  16.,  17.,  18.,  19.]],

        [[ 20.,  21.,  22.,  23.,  24.],
         [ 25.,  26.,  27.,  28.,  29.],
         [ 30.,  31.,  32.,  33.,  34.],
         [ 35.,  36.,  37.,  38.,  39.]],

        [[ 40.,  41.,  42.,  43.,  44.],
         [ 45.,  46.,  47.,  48.,  49.],
         [ 50.,  51.,  52.,  53.,  54.],
         [ 55.,  56.,  57.,  58.,  59.]]])
-----
x.permute(1, 0, 2).shape: 
 torch.Size([4, 3, 5])
x.permute(1, 0, 2): 
 tensor([[[  0.,   1.,   2.,   3.,   4.],
         [ 20.,  21.,  22.,  23.,  24.],
         [ 40.,  41.,  42.,  43.,  44.]],

        [[  5.,   6.,   7.,   8.,   9.],
         [ 25.,  26.,  27.,  28.,  29.],
         [ 45.,  46.,  47.,  48.,  49.]],

        [[ 10.,  11.,  12.,  13.,  14.],
         [ 30.,  31.,  32.,  33.,  34.],
         [ 50.,  51.,  52.,  53.,  54.]],

        [[ 

Matrix multiplication is `mm`:

In [4]:
x1 = torch.arange(6).view(2, 3).float()
describe(x1)

x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

describe(torch.mm(x1, x2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[ 1.,  2.],
        [ 1.,  2.],
        [ 1.,  2.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[  3.,   6.],
        [ 12.,  24.]])


In [28]:
x = torch.arange(0, 12).view(3,4).float()
print(x)

x2 = torch.ones(4, 2)
x2[:, 1] += 1
print(x2)

print(x.mm(x2))

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])
tensor([[ 1.,  2.],
        [ 1.,  2.],
        [ 1.,  2.],
        [ 1.,  2.]])
tensor([[  6.,  12.],
        [ 22.,  44.],
        [ 38.,  76.]])


See the [PyTorch Math Operations Documentation](https://pytorch.org/docs/stable/torch.html#math-operations) for more!

## Computing Gradients

In [29]:
x = torch.tensor([[2,3]], requires_grad=True, dtype=torch.float32)
z = 3 * x
print(z)

tensor([[ 6,  9]])


In this small snippet, you can see the gradient computations at work.  We create a tensor and multiply it by 3.  Then, we create a scalar output using `sum()`.  A Scalar output is needed as the the loss variable. Then, called backward on the loss means it computes its rate of change with respect to the inputs.  Since the scalar was created with sum, each position in z and x are independent with respect to the loss scalar. 

The rate of change of x with respect to the output is just the constant 3 that we multiplied x by.

In [30]:
x = torch.tensor([[2,3]], requires_grad=True, dtype=torch.float32)
print("x: \n", x)
print("---")
z = 3 * x
print("z = 3*x: \n", z)
print("---")

loss = z.sum()
print("loss = z.sum(): \n", loss)
print("---")

loss.backward()

print("after loss.backward(), x.grad: \n", x.grad)


x: 
 tensor([[ 2,  3]])
---
z = 3*x: 
 tensor([[ 6,  9]])
---
loss = z.sum(): 
 tensor(15)
---
after loss.backward(), x.grad: 
 tensor([[ 3,  3]])


### Example: Computing a conditional gradient

$$ \text{ Find the gradient of f(x) at x=1 } $$
$$ {} $$
$$ f(x)=\left\{
\begin{array}{ll}
    sin(x) \text{ if } x>0 \\
    cos(x) \text{ otherwise } \\
\end{array}
\right.$$

In [31]:
def f(x):
    # FILL THIS PART IN
    y = x
    return y

In [32]:
x = torch.tensor([1.0], requires_grad=True)
y = f(x)
y.backward()
print(x.grad)

tensor([ 0.5403])


We could apply this to a larger vector too, but we need to make sure the output is a scalar:

In [33]:
x = torch.tensor([1.0, 0.5], requires_grad=True)
y = f(x)
try:
    y.backward()
    print(x.grad)
except RuntimeError as re:
    print("THIS ERROR WAS EXPECTED: ", re)

RuntimeError: grad can be implicitly created only for scalar outputs

Making the output a scalar:

In [34]:
x = torch.tensor([1.0, 0.5], requires_grad=True)
y = f(x)
y.sum().backward()
print(x.grad)

tensor([ 0.5403,  0.8776])


but there was an issue.. this isn't right for this edge case:

In [35]:
x = torch.tensor([1.0, -1], requires_grad=True)
y = f(x)
y.sum().backward()
print(x.grad)

tensor([-0.8415,  0.8415])


In [36]:
x = torch.tensor([-0.5, -1], requires_grad=True)
y = f(x)
y.sum().backward()
print(x.grad)

tensor([ 0.4794,  0.8415])


This is because we aren't doing the boolean computation and subsequent application of cos and sin on an elementwise basis.  So, to solve this, it is common to use masking:

In [37]:
def f2(x):
    # WRITE SOLUTION HERE
    y = x
    return y

x = torch.tensor([1.0, -1], requires_grad=True)
y = f2(x)
y.sum().backward()
print(x.grad)

tensor([ 0.5403,  0.8415])


In [47]:
def describe_grad(x):
    if x.grad is None:
        print("No gradient information")
    else:
        print("Gradient: \n{}".format(x.grad))
        print("Gradient Function: {}".format(x.grad_fn))

In [62]:
import torch
x = torch.ones(2, 2, requires_grad=True)
describe(x)
describe_grad(x)


y = (x + 2) * (x + 5) + 3
describe(y)
z = y.mean()
describe(z)
describe_grad(x)

z.backward(create_graph=True, retain_graph=True)
describe_grad(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 1.,  1.],
        [ 1.,  1.]])
No gradient information
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 21.,  21.],
        [ 21.,  21.]])
Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
No gradient information
Gradient: 
tensor([[ 2.2500,  2.2500],
        [ 2.2500,  2.2500]])
Gradient Function: None


### Exploring gradients

Below is essentially a scratch pad :)

In [55]:
x = torch.ones(2, 2, requires_grad=True)

In [56]:
y = x + 2

In [57]:
y.grad_fn

In [58]:
z = y * y * 3
out = z.mean()

In [59]:
out.backward()

In [26]:
torch.is_tensor(out.grad_fn)

False

In [27]:
hasattr(out.grad_fn, 'variable')

False

In [35]:
out.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[0][0].next_functions[0][0].next_functions

()

### CUDA Tensors

PyTorch's operations can seamlessly be used on the GPU or on the CPU.  There are a couple basic operations for interacting in this way.

In [3]:
print(torch.cuda.is_available())

True


In [8]:
x = torch.rand(3,3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[ 0.7453,  0.8045,  0.2022],
        [ 0.7781,  0.0699,  0.7157],
        [ 0.5425,  0.7718,  0.0086]])


In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [9]:
x = torch.rand(3, 3).to(device)
describe(x)
print(x.device)

Type: torch.cuda.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[ 0.6902,  0.7547,  0.5336],
        [ 0.1381,  0.0748,  0.5548],
        [ 0.0975,  0.0272,  0.5688]], device='cuda:0')
cuda:0


In [10]:
cpu_device = torch.device("cpu")

In [11]:
y = torch.rand(3, 3)
x + y

RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #3 'other'

In [12]:
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

tensor([[ 0.7159,  1.0685,  1.3509],
        [ 0.3912,  0.2838,  1.3202],
        [ 0.2967,  0.0420,  0.6559]])

In [6]:
if torch.cuda.is_available(): # only is GPU is available
    a = torch.rand(3,3).to(device='cuda:0') #  CUDA Tensor
    print(a)
    
    b = torch.rand(3,3).cuda()
    print(b)

    print(a + b)

    a = a.cpu() # Error expected
    print(a + b)

tensor([[ 0.2388,  0.7313,  0.6012],
        [ 0.3043,  0.2548,  0.6294],
        [ 0.9665,  0.7399,  0.4517]], device='cuda:0')
tensor([[ 0.4757,  0.7842,  0.1525],
        [ 0.6662,  0.3343,  0.7893],
        [ 0.3216,  0.5247,  0.6688]], device='cuda:0')
tensor([[ 0.7145,  1.5155,  0.7537],
        [ 0.9706,  0.5891,  1.4187],
        [ 1.2882,  1.2647,  1.1206]], device='cuda:0')


RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #3 'other'

### Exercises

Some of these exercises require operations not covered in the notebook.  You will have to look at [the documentation](https://pytorch.org/docs/) (on purpose!)


(Answers are at the bottom)

#### Exercise 1

Create a 2D tensor and then add a dimension of size 1 inserted at the 0th axis.

#### Exercise 2

Remove the extra dimension you just added to the previous tensor.

#### Exercise 3

Create a random tensor of shape 5x3 in the interval [3, 7)

#### Exercise 4

Create a tensor with values from a normal distribution (mean=0, std=1).

#### Exercise 5

Retrieve the indexes of all the non zero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).

#### Exercise 6

Create a random tensor of size (3,1) and then horizonally stack 4 copies together.

#### Exercise 7

Return the batch matrix-matrix product of two 3 dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

#### Exercise 8

Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).

Answers below

Answers still below.. Keep Going

#### Exercise 1

Create a 2D tensor and then add a dimension of size 1 inserted at the 0th axis.

In [40]:
a = torch.rand(3,3)
a = a.unsqueeze(0)
print(a)
print(a.shape)

tensor([[[ 0.7077,  0.4189,  0.0655],
         [ 0.8839,  0.8083,  0.7528],
         [ 0.8988,  0.6839,  0.7658]]])
torch.Size([1, 3, 3])


#### Exercise 2 

Remove the extra dimension you just added to the previous tensor.

In [41]:
a = a.squeeze(0)
print(a.shape)

torch.Size([3, 3])


#### Exercise 3

Create a random tensor of shape 5x3 in the interval [3, 7)

In [42]:
3 + torch.rand(5, 3) * 4

tensor([[ 6.6597,  4.5970,  3.4402],
        [ 4.0164,  4.7330,  4.7802],
        [ 4.9864,  6.1461,  5.6416],
        [ 3.5212,  4.3992,  4.5295],
        [ 6.2172,  4.2744,  4.1632]])

#### Exercise 4

Create a tensor with values from a normal distribution (mean=0, std=1).

In [43]:
a = torch.rand(3,3)
a.normal_(mean=0, std=1)

tensor([[-0.2107,  1.1399, -2.5122],
        [ 1.3823,  0.9847,  1.4719],
        [ 0.3100,  1.5829,  0.2351]])

#### Exercise 5

Retrieve the indexes of all the non zero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).

In [44]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.nonzero(a)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 4]])

#### Exercise 6

Create a random tensor of size (3,1) and then horizonally stack 4 copies together.

In [45]:
a = torch.rand(3,1)
a.expand(3,4)

tensor([[ 0.7595,  0.7595,  0.7595,  0.7595],
        [ 0.5311,  0.5311,  0.5311,  0.5311],
        [ 0.6449,  0.6449,  0.6449,  0.6449]])

#### Exercise 7

Return the batch matrix-matrix product of two 3 dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

In [46]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
torch.bmm(a, b)

tensor([[[ 1.7768,  1.5815,  1.7667,  0.9918],
         [ 0.7049,  0.7050,  0.6055,  0.3455],
         [ 1.5937,  1.3627,  1.6757,  1.0042],
         [ 1.2478,  0.9978,  0.8067,  1.1299]],

        [[ 1.4816,  1.4685,  1.7443,  1.6224],
         [ 0.8311,  1.1861,  1.2165,  0.9788],
         [ 1.3339,  1.3306,  1.7348,  1.3621],
         [ 1.3177,  1.5979,  1.5706,  1.3298]],

        [[ 1.8358,  0.8323,  1.2206,  1.3237],
         [ 2.0028,  1.5150,  1.5610,  1.2854],
         [ 2.2775,  1.6230,  1.9977,  1.8435],
         [ 2.5799,  1.6463,  1.8448,  1.7839]]])

#### Exercise 8

Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).

In [47]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[ 1.7612,  1.5625,  1.6402,  1.3563],
         [ 1.8779,  1.5361,  1.5207,  1.1499],
         [ 1.0956,  0.6416,  0.6545,  0.7713],
         [ 1.7553,  1.0487,  1.0097,  0.9493]],

        [[ 1.0501,  0.7754,  0.7437,  0.6454],
         [ 1.4964,  1.3167,  1.3392,  1.0311],
         [ 1.9306,  1.4569,  1.5652,  1.4622],
         [ 2.1869,  1.7187,  1.5579,  1.1575]],

        [[ 1.1794,  0.8222,  0.7826,  0.7259],
         [ 1.3814,  0.9908,  0.9205,  0.7621],
         [ 2.9413,  2.0567,  1.9665,  1.7345],
         [ 2.1376,  1.4964,  1.4937,  1.4069]]])

### END